project:
  type: manuscript
  output-dir: docs
  
manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
 

execute:
  freeze: true

editor: visual

title: "Association Between Prior Cesarean Delivery and IVF Outcome: A Case–Control Study Protocol"

authors:
  - name: Abd Elatif Swailam
    affiliation: IVF Center.
  - name: Sara Abdelkader
    affiliation: Egyptian Center for Evidence Based Medicine
  - name: Ayman Negm
    affiliation: IVF Center.
  - name: Mourad El-Fahham
    affiliation: Ain Shams University.    
  - name: Ashraf Nabhan
    affiliation: MTI University.

bibliography: references.bib

csl: vancouver.csl